"""empty message

Revision ID: 96518bac7c0d
Revises: 28bd5d423bf6
Create Date: 2020-06-18 23:19:06.198360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96518bac7c0d'
down_revision = '28bd5d423bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Area',
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_foreign_key(None, 'Venue', 'Area', ['city'], ['city'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_table('Area')
    # ### end Alembic commands ###
